cmp:
	@echo " Compiling...";
	g++ -g main.cpp ./src/*.cpp ./src/Grid/*.cpp ./src/Livings/*.cpp ./src/Livings/Heroes/*.cpp ./src/Livings/Monsters/*.cpp ./src/Usables/*.cpp ./src/Usables/Items/*.cpp ./src/Usables/Spells/*.cpp ./src/Usables/Inventory/*.cpp -o build/run

	