cmp:
	@echo " Compiling...";
	g++ -g main.cpp ./src/*.cpp  ./src/data_structures/map/*.cpp ./src/data_structures/heap/*.cpp ./src/data_structures/posting_list/*.cpp ./src/data_structures/trie/*.cpp ./src/data_structures/stack/*.cpp ./src/data_structures/search_result/*.cpp ./src/string/*.cpp -o ./minisearch